# Tomcat
server:
    name: iBase4J-SYS-Web
    port: 8088
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
# mysql
spring:
    # 环境 dev|test|prod
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    thymeleaf:
        cache: false
    session:
        store-type: none
    http:
        #上传文件大小设置
        multipart:
            maxFileSize: 10Mb
            maxRequestSize: 50Mb